"""add host_profile_url

Revision ID: 39faf305db47
Revises: 40dc1bb796e8
Create Date: 2026-08-06 04:51:25.046507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39faf305db47'
down_revision: Union[str, Sequence[str], None] = '40dc1bb796e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('host_profile_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'host_profile_url')
    # ### end Alembic commands ###
