"""Add DLQ fields to RateHistory and ScrapeRun

Revision ID: 40dc1bb796e8
Revises: 0944da1ccf32
Create Date: 2026-08-03 16:49:23.384868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40dc1bb796e8'
down_revision: Union[str, Sequence[str], None] = '0944da1ccf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_history', sa.Column('dlq_html_url', sa.Text(), nullable=True))
    op.add_column('rate_history', sa.Column('dlq_screenshot_url', sa.Text(), nullable=True))
    op.add_column('scrape_runs', sa.Column('anomalies_captured', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'anomalies_captured')
    op.drop_column('rate_history', 'dlq_screenshot_url')
    op.drop_column('rate_history', 'dlq_html_url')
    # ### end Alembic commands ###
