"""Add consecutive_404s to property

Revision ID: 47b6bac2ab60
Revises: 8f7bbf88bdff
Create Date: 2026-07-18 21:45:18.795770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b6bac2ab60'
down_revision: Union[str, Sequence[str], None] = '8f7bbf88bdff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('consecutive_404s', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'consecutive_404s')
    # ### end Alembic commands ###
