"""add_re_knowledge_base_table

Revision ID: 6a46625d04fa
Revises: 39faf305db47
Create Date: 2026-08-07 18:04:48.557026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '6a46625d04fa'
down_revision: Union[str, Sequence[str], None] = '39faf305db47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector SCHEMA extensions;")
    op.create_table('re_knowledge_base',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=False),
    sa.Column('chunk_content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_re_kb_embedding', 're_knowledge_base', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.execute("GRANT SELECT ON public.re_knowledge_base TO anon, authenticated;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_re_kb_embedding', table_name='re_knowledge_base', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('re_knowledge_base')
    # ### end Alembic commands ###
