"""Add consecutive_404s to Product

Revision ID: 835b6d864446
Revises: c9f3a2b7e110
Create Date: 2026-07-23 12:35:09.845159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835b6d864446'
down_revision: Union[str, Sequence[str], None] = 'c9f3a2b7e110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('consecutive_404s', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'consecutive_404s')
    # ### end Alembic commands ###
