"""Add REAL_ESTATE_MONITOR and ScrapeRun.meta_data

Revision ID: 8f7bbf88bdff
Revises: e5ffe562acf9
Create Date: 2026-07-18 13:41:05.158864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f7bbf88bdff'
down_revision: Union[str, Sequence[str], None] = 'e5ffe562acf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_runs', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    
    # Alembic cannot autogenerate Postgres enum ADD VALUE
    op.execute("ALTER TYPE runjobtype ADD VALUE IF NOT EXISTS 'real_estate_monitor'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'meta_data')
    # ### end Alembic commands ###
