"""Add real estate tables and missing fields

Revision ID: e5ffe562acf9
Revises: 
Create Date: 2026-07-18 07:56:54.988575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5ffe562acf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('contact_email', sa.String(length=300), nullable=True),
    sa.Column('vertical', sa.Enum('ECOMMERCE', 'REAL_ESTATE', name='clientvertical', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_vertical'), 'clients', ['vertical'], unique=False)
    op.create_table('properties',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('property_key', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('market', sa.String(length=200), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('host_name', sa.String(length=300), nullable=True),
    sa.Column('cleaning_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_properties_client_id'), 'properties', ['client_id'], unique=False)
    op.create_index(op.f('ix_properties_platform'), 'properties', ['platform'], unique=False)
    op.create_index(op.f('ix_properties_property_key'), 'properties', ['property_key'], unique=False)
    op.create_table('rate_history',
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('stay_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nightly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_history_property_id'), 'rate_history', ['property_id'], unique=False)
    op.create_index(op.f('ix_rate_history_stay_date'), 'rate_history', ['stay_date'], unique=False)
    op.add_column('leads', sa.Column('related_alert_id', sa.Uuid(), nullable=True))
    op.add_column('leads', sa.Column('pitch_summary', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('outreach_status', sa.Enum('NOT_CONTACTED', 'CONTACTED', 'REPLIED', 'CLOSED', 'DEAD', name='outreachstatus', native_enum=False, length=20), nullable=False, server_default='NOT_CONTACTED'))
    
    op.execute("UPDATE leads SET contacts = '{}'::jsonb WHERE contacts IS NULL")
    op.alter_column('leads', 'contacts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
               
    op.execute("UPDATE leads SET socials = '{}'::jsonb WHERE socials IS NULL")
    op.alter_column('leads', 'socials',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
               
    op.create_foreign_key(None, 'leads', 'price_alerts', ['related_alert_id'], ['id'], ondelete='SET NULL')
    
    op.add_column('price_history', sa.Column('in_stock', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('price_history', sa.Column('merchant', sa.String(length=255), nullable=True))
    op.add_column('price_history', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.alter_column('price_history', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
               
    op.add_column('products', sa.Column('sku', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(length=200), nullable=True))
    op.add_column('products', sa.Column('retailer', sa.String(length=100), nullable=False, server_default='Unknown'))
    op.add_column('products', sa.Column('client_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_client_id'), 'products', ['client_id'], unique=False)
    op.create_index(op.f('ix_products_retailer'), 'products', ['retailer'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_foreign_key(None, 'products', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    op.add_column('scrape_runs', sa.Column('platform', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'platform')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_retailer'), table_name='products')
    op.drop_index(op.f('ix_products_client_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_column('products', 'client_id')
    op.drop_column('products', 'retailer')
    op.drop_column('products', 'category')
    op.drop_column('products', 'sku')
    op.alter_column('price_history', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('price_history', 'meta_data')
    op.drop_column('price_history', 'merchant')
    op.drop_column('price_history', 'in_stock')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.alter_column('leads', 'socials',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('leads', 'contacts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('leads', 'outreach_status')
    op.drop_column('leads', 'pitch_summary')
    op.drop_column('leads', 'related_alert_id')
    op.drop_index(op.f('ix_rate_history_stay_date'), table_name='rate_history')
    op.drop_index(op.f('ix_rate_history_property_id'), table_name='rate_history')
    op.drop_table('rate_history')
    op.drop_index(op.f('ix_properties_property_key'), table_name='properties')
    op.drop_index(op.f('ix_properties_platform'), table_name='properties')
    op.drop_index(op.f('ix_properties_client_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_clients_vertical'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
